# Generated by Django 4.0.4 on 2022-05-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todoitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_text', models.CharField(max_length=100)),
                ('todo_status', models.CharField(default='NOT DONE', max_length=5)),
            ],
        ),
    ]
