# Generated by Django 4.0.4 on 2022-05-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='todo_status',
            field=models.CharField(default='NOT DONE', max_length=8),
        ),
    ]
